#!/bin/sh

if [[ $# -ne 1 ]]; then
	echo "Please pass a file"
	exit 1
fi

EFI_PATH="$1"

if [[ ! -f "$EFI_PATH" ]]; then
	echo "Please pass a FILE"
	exit 1
fi

TMPDIR_IMG=$(mktemp -d)
TMPDIR_MNT="$TMPDIR_IMG/m"
mkdir "$TMPDIR_MNT"

IMG_PATH="$TMPDIR_IMG/disk.img"
dd if=/dev/zero of="$IMG_PATH" bs=1M count=32
mkfs.vfat "$IMG_PATH"

sudo mount -o loop "$IMG_PATH" "$TMPDIR_MNT"
sudo mkdir -p "$TMPDIR_MNT/EFI/BOOT"
sudo cp "$EFI_PATH" "$TMPDIR_MNT/EFI/BOOT/BOOTX64.EFI"
sync

sudo umount "$TMPDIR_MNT"
rmdir "$TMPDIR_MNT"

qemu-system-x86_64 -drive if=pflash,format=raw,readonly=on,file=/usr/share/edk2/x64/OVMF_CODE.4m.fd -drive format=raw,file="$IMG_PATH"

rm "$IMG_PATH"
rmdir "$TMPDIR_IMG"
